version: "3.9"
services:
  api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        ports:
            - "8080:3000"
            
  postgresql:
    image: postgres
    environment:
      environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "notes"
    ports:
      - "5432:5432"