version: "3.9"
services:
  app:
    # image: nest-dockerized
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on: 
      - postgres
    hostname: localhost
    environment: 
      DATABASE_URL: postgres://user:password@postgres:5432/notes
    ports:
       - 8080:3000

  postgres:
        image: postgres:latest
        ports:
          - 35000:5432
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: notes